default-bank:
  bank:
    name: "LLC DefaultBank"
    partner:
      prefix-url: "http://localhost:8080"
server:
  port: 8081
spring:
  main:
    allow-bean-definition-overriding: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      show-sql: false
      ddl-auto: validate
    defer-datasource-initialization: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      allow-pool-suspension: true
    driverClassName: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  config:
    import:
      optional: .env
logging:
  file:
    name: src/main/resources/application_logs.txt
  level:
    org:
      springframework:
        security: DEBUG
        web:
          cors: DEBUG
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: INFO
  logback:
    rolling policy:
      max-history: 30
      max-file-size: 5MB

jwt:
  access-token-lifetime: 15m
  refresh-token-lifetime: 30d
  id-token-lifetime: 30d
  not-before: 10s
  filename: ${JWT_SECRET_FILE_NAME}
  audience: "online_bank audience"
  issuer: "com.example"

app:
  cors:
    allowed-origins: ${CORS_URL}
#app:
#  cors:
#    allowed-origins: http://localhost:3000

resend:
  api-key: ${RESEND_API_KEY}
